<?php

/**
 * Scope 2 Purchased Energy - sub-categories (electricity, heating, cooling),
 * emission sources with units and factors, and grid emission factors by region.
 */
return [
    'grid_ef' => [
        ['region' => 'UAE (Abu Dhabi / ADWEC)', 'co2' => 0.4041, 'src' => 'IEA 2024'],
        ['region' => 'UAE (Dubai / DEWA)', 'co2' => 0.3876, 'src' => 'DEWA 2023'],
        ['region' => 'UAE (Sharjah / SEWA)', 'co2' => 0.4200, 'src' => 'IEA est.'],
        ['region' => 'Saudi Arabia', 'co2' => 0.5320, 'src' => 'IEA 2024'],
        ['region' => 'Qatar', 'co2' => 0.4890, 'src' => 'IEA 2024'],
        ['region' => 'Bahrain', 'co2' => 0.5180, 'src' => 'IEA 2024'],
        ['region' => 'Kuwait', 'co2' => 0.5690, 'src' => 'IEA 2024'],
        ['region' => 'Oman', 'co2' => 0.4540, 'src' => 'IEA 2024'],
        ['region' => 'Egypt', 'co2' => 0.4520, 'src' => 'IEA 2024'],
        ['region' => 'Jordan', 'co2' => 0.4310, 'src' => 'IEA 2024'],
        ['region' => 'India', 'co2' => 0.7080, 'src' => 'IEA 2024'],
        ['region' => 'China', 'co2' => 0.5440, 'src' => 'IEA 2024'],
        ['region' => 'USA (National Avg)', 'co2' => 0.3710, 'src' => 'EPA eGRID'],
        ['region' => 'UK', 'co2' => 0.2070, 'src' => 'DESNZ 2024'],
        ['region' => 'Germany', 'co2' => 0.3610, 'src' => 'IEA 2024'],
        ['region' => 'France', 'co2' => 0.0520, 'src' => 'IEA 2024'],
        ['region' => 'Australia', 'co2' => 0.6560, 'src' => 'IEA 2024'],
        ['region' => 'Japan', 'co2' => 0.4340, 'src' => 'IEA 2024'],
        ['region' => 'Canada', 'co2' => 0.1200, 'src' => 'IEA 2024'],
        ['region' => 'Brazil', 'co2' => 0.0740, 'src' => 'IEA 2024'],
        ['region' => 'South Africa', 'co2' => 0.8980, 'src' => 'IEA 2024'],
        ['region' => 'World Average', 'co2' => 0.4940, 'src' => 'IEA 2024'],
        ['region' => 'Custom (enter manually)', 'co2' => 0, 'src' => 'User-defined'],
    ],

    'electricity' => [
        ['name' => 'Backup / Emergency Generator Power', 'desc' => 'Purchased backup power from third-party generators', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Grid EF applied - third-party generator electricity'],
        ['name' => 'CHP / Cogeneration - Electricity', 'desc' => 'Combined heat & power electricity portion', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'CHP electricity allocation - grid EF'],
        ['name' => 'EV Charging (Third-Party)', 'desc' => 'Electricity from third-party EV charging stations', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Grid EF applied to third-party EV charging'],
        ['name' => 'Green Tariff Electricity', 'desc' => 'Electricity from utility green/renewable tariff', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Market-based EF from green tariff supplier'],
        ['name' => 'Landlord-Supplied Electricity', 'desc' => 'Electricity supplied via building landlord/manager', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Grid EF - landlord sub-metered electricity'],
        ['name' => 'Power Purchase Agreement (PPA)', 'desc' => 'Electricity from third-party PPA contract', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Market-based EF from PPA contract'],
        ['name' => 'Purchased Electricity (Location-Based)', 'desc' => 'Grid electricity - location-based method', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'IEA/eGRID grid avg EF by country (location-based)'],
        ['name' => 'Purchased Electricity (Market-Based)', 'desc' => 'Grid electricity - market-based method', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Supplier-specific or residual mix EF (market-based)'],
        ['name' => 'RECs / GOs / I-RECs', 'desc' => 'Renewable Energy Certificates / Guarantees of Origin', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'efPerKwh' => 0, 'note' => 'Zero EF with valid RECs/GOs/I-RECs (market-based)'],
        ['name' => 'Shared Facility Electricity', 'desc' => 'Electricity allocated from shared/multi-tenant facility', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Grid EF - allocated share of facility electricity'],
        ['name' => 'Third-Party On-Site Solar/Wind', 'desc' => 'On-site renewable from third-party owned system', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Market-based EF from third-party on-site renewable'],
        ['name' => 'Trigeneration - Electricity', 'desc' => 'CCHP electricity portion (cooling, heat, power)', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Trigeneration electricity allocation - grid EF'],
        ['name' => 'Virtual PPA (VPPA) Electricity', 'desc' => 'Electricity via virtual/financial PPA contract', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'Market-based EF from VPPA financial settlement'],
        ['name' => 'Custom Electricity Source', 'desc' => 'Other purchased electricity source not listed', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh']], 'isGrid' => true, 'note' => 'User-defined electricity source'],
    ],

    'heating' => [
        ['name' => 'Biomass District Heat', 'desc' => 'District heating from biomass/wood chip boilers', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.029, 'note' => 'Biomass district heat ~0.029 kgCO2e/kWh (DEFRA)'],
        ['name' => 'CHP / Cogeneration - Heat', 'desc' => 'Heat portion from combined heat & power plant', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.198, 'note' => 'CHP heat allocation ~0.198 kgCO2e/kWh (DEFRA)'],
        ['name' => 'District Heating (Gas-Fired)', 'desc' => 'District heating from natural gas network', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.198, 'note' => 'Gas-fired district heat 0.198 kgCO2e/kWh (DEFRA)'],
        ['name' => 'District Heating (Mixed/Unknown)', 'desc' => 'District heating - unspecified fuel source', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.198, 'note' => 'Avg district heat 0.198 kgCO2e/kWh (DEFRA)'],
        ['name' => 'District Heating (Oil-Fired)', 'desc' => 'District heating from fuel oil network', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.266, 'note' => 'Oil-fired district heat ~0.266 kgCO2e/kWh (IEA)'],
        ['name' => 'Geothermal Heat', 'desc' => 'Purchased heat from geothermal source', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.027, 'note' => 'Geothermal heat ~0.027 kgCO2e/kWh (IPCC)'],
        ['name' => 'Heat Pump Output (Third-Party)', 'desc' => 'Heat from third-party operated heat pump', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.120, 'note' => 'Heat pump output ~0.12 kgCO2e/kWh (electric-driven)'],
        ['name' => 'Industrial Waste Heat Recovery', 'desc' => 'Purchased recovered waste heat from industrial process', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.000, 'note' => 'Waste heat recovery - zero direct EF (allocation)'],
        ['name' => 'Landlord-Supplied Heating', 'desc' => 'Heating supplied via building landlord/manager', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.198, 'note' => 'Landlord heat - avg district EF 0.198 kgCO2e/kWh'],
        ['name' => 'Purchased Hot Water', 'desc' => 'Hot water from district/third-party system', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.198, 'note' => 'District hot water ~0.198 kgCO2e/kWh (DEFRA)'],
        ['name' => 'Purchased Steam (High Pressure)', 'desc' => 'Industrial high-pressure steam supply', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu'], ['u' => 'ton', 'label' => 'tonnes steam']], 'efPerKwh' => 0.170, 'note' => 'HP steam from gas boiler ~0.17 kgCO2e/kWh'],
        ['name' => 'Purchased Steam (Low Pressure)', 'desc' => 'Industrial low-pressure steam supply', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu'], ['u' => 'ton', 'label' => 'tonnes steam']], 'efPerKwh' => 0.150, 'note' => 'LP steam ~0.15 kgCO2e/kWh (lower temp/losses)'],
        ['name' => 'Solar Thermal Heat (Third-Party)', 'desc' => 'Heat from third-party solar thermal system', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.000, 'note' => 'Solar thermal - zero direct combustion EF'],
        ['name' => 'Trigeneration - Heat', 'desc' => 'Heat portion from CCHP/trigeneration plant', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.198, 'note' => 'Trigeneration heat allocation ~0.198 kgCO2e/kWh'],
        ['name' => 'Custom Heating Source', 'desc' => 'Other purchased heating source not listed', 'units' => [['u' => 'kWh', 'label' => 'kWh'], ['u' => 'MWh', 'label' => 'MWh'], ['u' => 'GJ', 'label' => 'GJ'], ['u' => 'MMBtu', 'label' => 'MMBtu']], 'efPerKwh' => 0.198, 'note' => 'User-defined heating source - default 0.198'],
    ],

    'cooling' => [
        ['name' => 'Absorption Chiller Cooling (Third-Party)', 'desc' => 'Cooling from third-party absorption chiller', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.180, 'note' => 'Absorption chiller cooling ~0.18 kgCO2e/kWh'],
        ['name' => 'Chilled Water (District)', 'desc' => 'Chilled water from district cooling provider', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.210, 'note' => 'District chilled water ~0.21 kgCO2e/kWh (UAE/GCC)'],
        ['name' => 'Data Center Cooling (Third-Party)', 'desc' => 'Cooling for IT equipment from third-party provider', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours']], 'efPerKwh' => 0.210, 'note' => 'Third-party data center cooling ~0.21 kgCO2e/kWh'],
        ['name' => 'District Cooling (Electricity-Driven)', 'desc' => 'District cooling from electric chillers', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.210, 'note' => 'Electric chiller district cooling ~0.21 kgCO2e/kWh'],
        ['name' => 'District Cooling (Gas-Driven)', 'desc' => 'District cooling from gas-fired absorption system', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.240, 'note' => 'Gas-driven district cooling ~0.24 kgCO2e/kWh'],
        ['name' => 'District Cooling (Mixed/Unknown)', 'desc' => 'District cooling - unspecified system type', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.210, 'note' => 'Avg district cooling ~0.21 kgCO2e/kWh'],
        ['name' => 'Free Cooling / Seawater Cooling', 'desc' => 'Cooling using seawater or ambient free cooling', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours']], 'efPerKwh' => 0.050, 'note' => 'Free/seawater cooling (pump energy) ~0.05 kgCO2e/kWh'],
        ['name' => 'Ice Storage Cooling', 'desc' => 'Cooling from off-peak ice storage system', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours']], 'efPerKwh' => 0.210, 'note' => 'Ice storage cooling ~0.21 kgCO2e/kWh (shifted load)'],
        ['name' => 'Landlord-Supplied Cooling', 'desc' => 'Cooling supplied via building landlord/manager', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours']], 'efPerKwh' => 0.210, 'note' => 'Landlord cooling - avg district EF ~0.21 kgCO2e/kWh'],
        ['name' => 'Trigeneration - Cooling', 'desc' => 'Cooling portion from CCHP/trigeneration plant', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.180, 'note' => 'Trigeneration cooling allocation ~0.18 kgCO2e/kWh'],
        ['name' => 'Custom Cooling Source', 'desc' => 'Other purchased cooling source not listed', 'units' => [['u' => 'kWh', 'label' => 'kWh (thermal)'], ['u' => 'MWh', 'label' => 'MWh (thermal)'], ['u' => 'ton-hr', 'label' => 'Ton-hours'], ['u' => 'GJ', 'label' => 'GJ']], 'efPerKwh' => 0.210, 'note' => 'User-defined cooling source - default 0.21'],
    ],
];
